# Generated by Django 3.2 on 2021-04-14 16:44

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.UUID('a728596d-b85b-4b62-bcab-9ec597dcebf7'), editable=False)),
                ('make', models.CharField(max_length=56)),
                ('color', models.CharField(max_length=56)),
                ('production_year', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2021), django.core.validators.MinValueValidator(1960)])),
                ('avg_fuel_consumption_per_100km', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(2)])),
                ('max_passengers', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
